---
# file: roles/postgresql/tasks/main.yml
- name: postgresql repo install
  yum: name={{item}} state=present
  with_items:
    - http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-2.noarch.rpm

- name: packages install
  yum: name={{item}} state=present
  with_items:
    - postgresql94-server

- name: create postgresql dir
  file: path={{item.path}} owner={{item.owner}} group={{item.group}} mode={{item.mode}} state=directory
  with_items:
    - { path: '/opt', owner: 'root', group: 'root', mode: '0755' }
    - { path: '/opt/pgsql', owner: 'postgres', group: 'postgres', mode: '0700' }
    - { path: '/opt/pgsql/pgdata', owner: 'postgres', group: 'postgres', mode: '0700' }
    - { path: '/opt/pgsql/pgxlog', owner: 'postgres', group: 'postgres', mode: '0700' }
    - { path: '/opt/pgsql/pgarch', owner: 'postgres', group: 'postgres', mode: '0700' }

- name: check initdb
  stat: path=/opt/pgsql/pgdata/PG_VERSION
  register: pgdata_installed
  changed_when: pgdata_installed.stat.exists == False

- name: postgresql initdb
  command: su - postgres -c "/usr/pgsql-9.4/bin/initdb -D /opt/pgsql/pgdata -X /opt/pgsql/pgxlog --encoding=UTF-8 --no-locale"
  when: pgdata_installed.stat.exists == False

- name: postgres bash profile
  template: src=dot_bash_profile.j2 dest=/var/lib/pgsql/.bash_profile owner=postgres group=postgres mode=700

- name: postgres sysconfig setting
  template: src=etc_sysconfig_pgsql_postgresql-9.4.j2 dest=/etc/sysconfig/pgsql/postgresql-9.4 owner=root group=root mode=644

- name: postgresql settings
  template: src={{item}}.j2 dest=/opt/pgsql/pgdata/{{item}} owner=postgres group=postgres mode=600
  with_items:
    - postgresql.conf
    - pg_hba.conf
  notify: postgresql restart

- name: postgresql start
  service: name=postgresql-9.4 state=started enabled=yes
