---
# file: roles/postgresql/tasks/main.yml
- name: postgresql repo install
  yum:
    name: "{{ item }}"
    state: present
  register: result
  until: result | success
  retries: 3
  delay: 5
  with_items:
    - "https://download.postgresql.org/pub/repos/yum/{{ pgdg_version|regex_replace('-.*', '') }}/redhat/rhel-{{ ansible_distribution_major_version }}-x86_64/pgdg-{{ ansible_distribution|lower }}{{ pgdg_version|regex_replace('-.*', '')|regex_replace('\\.', '') }}-{{ pgdg_version }}.noarch.rpm"
    - "https://dl.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/x86_64/{{ (ansible_distribution_major_version == '7')|ternary('e/','') }}epel-release-{{ epel_version }}.noarch.rpm"

- name: packages install
  yum:
    name: "{{item}}"
    state: present
  with_items:
    "{{ postgresql_pkg }}"

- name: create postgresql dir
  file:
    path: "{{item.path}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
    state: directory
  with_items:
    - { path: "{{ postgresql_top_dir }}", owner: 'postgres', group: 'postgres', mode: '0700' }
    - { path: "{{ postgresql_top_dir }}/pgdata", owner: 'postgres', group: 'postgres', mode: '0700' }
    - { path: "{{ postgresql_top_dir }}/pgxlog", owner: 'postgres', group: 'postgres', mode: '0700' }
    - { path: "{{ postgresql_top_dir }}/pgarch", owner: 'postgres', group: 'postgres', mode: '0700' }
    - { path: "{{ postgresql_top_dir }}/pgarch/arc1", owner: 'postgres', group: 'postgres', mode: '0700' }
    - { path: "/var/log/postgresql", owner: 'postgres', group: 'postgres', mode: '0755' }

- name: postgresql initdb
  command: su - postgres -c "/usr/pgsql-{{ pgdg_version|regex_replace('-.*', '') }}/bin/initdb -D {{ postgresql_top_dir }}/pgdata -X {{ postgresql_top_dir }}/pgxlog/pg_xlog --encoding=UTF-8 --no-locale"
  args:
    creates: "{{ postgresql_top_dir }}/pgdata/PG_VERSION"

- name: postgres bash profile
  template:
    src: dot_bash_profile.j2
    dest: /var/lib/pgsql/.bash_profile
    owner: postgres
    group: postgres
    mode: 700
  notify: postgresql restart

- name: postgres sysconfig setting
  template:
    src: etc_sysconfig_pgsql_postgresql.j2
    dest: "/etc/sysconfig/pgsql/postgresql-{{ pgdg_version|regex_replace('-.*', '') }}"
    owner: root
    group: root
    mode: 644
  notify: postgresql restart
  when: ansible_distribution_major_version == "6"

- name: create postgresql systemd dir
  file:
    path: "/etc/systemd/system/postgresql-{{ pgdg_version|regex_replace('-.*', '') }}.service.d"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: ansible_distribution_major_version == "7"

- name: postgresql PGDATA settings
  template:
    src: pgdata.conf.j2
    dest: "/etc/systemd/system/postgresql-{{ pgdg_version|regex_replace('-.*', '') }}.service.d/pgdata.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: postgresql restart
  when: ansible_distribution_major_version == "7"

- name: vm.nr_hugepages check
  command: sysctl -n vm.nr_hugepages
  register: vm_nr_hugepages
  changed_when: false

- name: postgresql settings
  template:
    src: "{{item}}.j2"
    dest: "/opt/pgsql/pgdata/{{item}}"
    owner: postgres
    group: postgres
    mode: 600
  with_items:
    - postgresql.conf
    - pg_hba.conf
  notify: postgresql restart

- name: postgresql start
  service:
    name: "postgresql-{{ pgdg_version|regex_replace('-.*', '') }}"
    state: started
    enabled: yes
    daemon_reload: yes
