---
# file: roles/postgresql/tasks/main.yml
- name: packages install
  yum: name={{item}} state=present
  with_items:
    - postgresql-server

- name: postgresql initdb
  command: service postgresql initdb creates=/var/lib/pgsql/data/PG_VERSION
