---
# file: roles/postgresql/tasks/pg_partition.yml
- name: "create postgresql dir [{{ partition_item.path }}]"
  file:
    path: "{{ partition_item.path }}"
    owner: "{{ partition_item.owner }}"
    group: "{{ partition_item.group }}"
    mode: "{{ partition_item.mode}}"
    state: directory

- block:
  ### Begin Ansible 2.3 bug fix
  - name: "disk label check [{{ partition_item.path }}]"
    shell: "parted -s -m {{ partition_item.disk }} print | sed -n 2p | awk -F: '{print $6}'"
    register: disk_label_check
    changed_when: false

  - name: "mklabel [{{ partition_item.path }}]"
    parted:
      device: "{{ partition_item.disk }}"
      label: gpt
      state: present
    environment:
      LANG: en_US.UTF-8
    when: disk_label_check.stdout != 'gpt'

  - name: "parted device [{{ partition_item.path }}]"
    parted:
      device: "{{ partition_item.disk }}"
      number: 1
      state: present
    environment:
      LANG: en_US.UTF-8
  ### End Ansible 2.3 bug fix

  - name: "create fs [{{ partition_item.path }}]"
    filesystem:
      fstype: xfs
      dev: "{{ partition_item.disk }}1"

  - name: "mount disk [{{ partition_item.path }}]"
    mount:
      path: "{{ partition_item.path }}"
      src: "{{ partition_item.disk }}1"
      fstype: xfs
      state: mounted

  - name: "mounted partition permission [{{ partition_item.path }}]"
    file:
      path: "{{ partition_item.path }}"
      owner: "{{ partition_item.owner }}"
      group: "{{ partition_item.group }}"
      mode: "{{ partition_item.mode}}"
      state: directory

  when: >
    partition_item.disk is defined and
    partition_item.disk != ""
