---
# file: roles/postgresql/tasks/pg_partition.yml
- name: "create postgresql dir [{{ partition_item.path }}]"
  file:
    path: "{{ partition_item.path }}"
    owner: "{{ partition_item.owner }}"
    group: "{{ partition_item.group }}"
    mode: "{{ partition_item.mode}}"
    state: directory

- block:
  - name: "parted device [{{ partition_item.path }}]"
    parted:
      device: "{{ partition_item.disk }}"
      label: gpt
      number: 1
      state: present

  - name: "create fs [{{ partition_item.path }}]"
    filesystem:
      fstype: xfs
      dev: "{{ partition_item.disk }}1"

  - name: "mount disk [{{ partition_item.path }}]"
    mount:
      path: "{{ partition_item.path }}"
      src: "{{ partition_item.disk }}1"
      fstype: xfs
      state: mounted

  - name: "mounted partition permission [{{ partition_item.path }}]"
    file:
      path: "{{ partition_item.path }}"
      owner: "{{ partition_item.owner }}"
      group: "{{ partition_item.group }}"
      mode: "{{ partition_item.mode}}"
      state: directory

  when: >
    partition_item.disk is defined and
    partition_item.disk != ""
