---
# file: all.yml
- hosts: all
  roles:
    - { role: common, when: "ansible_os_family == 'RedHat' and exec_common_role" }
    - { role: postgresql, when: "ansible_os_family == 'RedHat'" }
    - { role: pg_stats_reporter, when: "ansible_os_family == 'RedHat'" }

  environment:
    "{{ proxy_env }}"

- hosts: postgresql
  roles:
    - { role: common, when: "ansible_os_family == 'RedHat' and exec_common_role" }
    - { role: postgresql, when: "ansible_os_family == 'RedHat'" }

  environment:
    "{{ proxy_env }}"

- hosts: pg_stats_reporter
  roles:
    - { role: common, when: "ansible_os_family == 'RedHat' and exec_common_role" }
    - { role: pg_stats_reporter, when: "ansible_os_family == 'RedHat'" }

  environment:
    "{{ proxy_env }}"
