---
# file: all.yml
- hosts: all
  roles:
    - { role: common, when: "ansible_os_family == 'RedHat' and exec_common_role" }
    - { role: postgresql, when: "ansible_os_family == 'RedHat'" }

  environment:
    "{{ proxy_env }}"
