---
# tasks file for pg_stats_reporter
- name: (rhel) pg_stats_reporter dependency package
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: "rhel-{{ ansible_distribution_major_version }}-server-optional-rpms"
  register: result
  until: result | success
  retries: 3
  delay: 5
  with_items:
    - httpd
    - php
    - php-pgsql
    - php-intl
    - php-cli
  when: ansible_distribution == "RedHat"

- name: (centos) pg_stats_reporter dependency package
  yum:
    name: "{{ item }}"
    state: present
  register: result
  until: result | success
  retries: 3
  delay: 5
  with_items:
    - httpd
    - php
    - php-pgsql
    - php-intl
    - php-cli
  when: ansible_distribution == "CentOS"

- name: pg_stats_reporter install
  yum:
    name: "https://downloads.sourceforge.net/project/pgstatsinfo/pg_stats_reporter/{{ pg_stats_reporter_version|regex_replace('-.*', '') }}/pg_stats_reporter-{{ pg_stats_reporter_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  register: result
  until: result | success
  retries: 3
  delay: 5
