---
# tasks file for pg_stats_reporter
- name: (rhel) pg_stats_reporter dependency package
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: "rhel-{{ ansible_distribution_major_version }}-server-optional-rpms"
  register: result
  until: result is success
  retries: 3
  delay: 5
  with_items:
    - httpd
    - php
    - php-pgsql
    - php-intl
    - php-cli
  when: ansible_distribution == "RedHat"

- name: (centos) pg_stats_reporter dependency package
  yum:
    name: "{{ item }}"
    state: present
  register: result
  until: result is success
  retries: 3
  delay: 5
  with_items:
    - httpd
    - php
    - php-pgsql
    - php-intl
    - php-cli
  when: ansible_distribution == "CentOS"

- name: pg_stats_reporter install
  yum:
    name: "https://downloads.sourceforge.net/project/pgstatsinfo/pg_stats_reporter/{{ pg_stats_reporter_version|regex_replace('-.*', '') }}/pg_stats_reporter-{{ pg_stats_reporter_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  register: result
  until: result is success
  retries: 3
  delay: 5

- block:
  - name: pg_stats_reporter setting
    template:
      src: pg_stats_reporter.ini.j2
      dest: /etc/pg_stats_reporter.ini
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_pg_stats_reporter_ini_setting
    notify: httpd restart

  always:
  - name: pg_stats_reporter backup settings
    include_tasks: backup.yml
    with_flattened:
      - "{{ is_pg_stats_reporter_ini_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: httpd start
  service:
    name: httpd
    state: started
    enabled: yes
