---
# file: roles/postgresql/defaults/main.yml
postgresql_top_dir: "/opt/pg"
pgdg_version: "9.6-3"
epel_version: "7-9"
postgresql_pkg:
  - "postgresql{{ pgdg_version|regex_replace('-.*', '')|regex_replace('\\.', '') }}-server"
#  - "postgis2_{{ pgdg_version|regex_replace('-.*', '')|regex_replace('\\.', '') }}"
