---
# file: roles/postgresql/defaults/main.yml
postgresql_top_dir: "/opt/pg"
pgdg_version: "9.6-3"
epel_version: "7-9"
pg_statsinfo_version: "3.2.3-1"
postgresql_pkg:
  - "postgresql{{ pgdg_version|regex_replace('-.*', '')|regex_replace('\\.', '') }}"
  - "postgresql{{ pgdg_version|regex_replace('-.*', '')|regex_replace('\\.', '') }}-libs"
  - "postgresql{{ pgdg_version|regex_replace('-.*', '')|regex_replace('\\.', '') }}-server"
  - "postgresql{{ pgdg_version|regex_replace('-.*', '')|regex_replace('\\.', '') }}-contrib"
  - "postgresql{{ pgdg_version|regex_replace('-.*', '')|regex_replace('\\.', '') }}-docs"
#  - "postgis2_{{ pgdg_version|regex_replace('-.*', '')|regex_replace('\\.', '') }}"
pg_stat_statement_only_enabled: True
pg_statsinfo_enabled: True
pg_statsinfo_user: "statsinfo"
pg_statsinfo_database: "stats"

############################################################
# postgresq.conf parameter
############################################################
pg_listen_addresses: "*"
pg_max_connections: 100
pg_superuser_reserved_connections: 10
pg_tcp_keepalives_idle: 60
pg_tcp_keepalives_interval: 5
pg_tcp_keepalives_count: 5
pg_shared_buffers: "{{ ansible_memtotal_mb // 10 }}" # MB
pg_work_mem: 4 # MB
pg_wal_level: archive
pg_checkpoint_segments: 64
pg_checkpoint_timeout: 15 # min
pg_max_wal_size: 1024 # MB
pg_min_wal_size: 1024 # MB
pg_checkpoint_completion_target: 0.7
pg_archive_command: "/bin/cp %p {{ postgresql_top_dir }}/pgarch/arc1/%f"
pg_random_page_cost: 4.0
pg_effective_cache_size: "{{ (ansible_memtotal_mb / 2 / 1024)|round(0, 'ceil')|int }}" # GB
pg_log_directory: "/var/log/postgresql"
pg_log_filename: "postgresql-%Y-%m-%d.log"
pg_log_min_duration_statement: 5 # second
pg_log_checkpoints: "on"
pg_log_error_verbosity: "verbose"
pg_log_line_prefix: "%t %p %c-%l %x %q(%u, %d, %r, %a) " # equal pg_statsinfo.textlog_line_prefix
pg_log_lock_waits: "on"
pg_log_autovacuum_min_duration: 0
pg_autovacuum_freeze_max_age: 2000000000
pg_autovacuum_vacuum_cost_limit: 400
pg_pg_statsinfo_snapshot_interval: 10 # min
pg_pg_statsinfo_enable_maintenance: "on"
pg_pg_statsinfo_maintenance_time: "00:02:00"
pg_pg_statsinfo_repository_keepday: 31
pg_pg_statsinfo_repolog_min_messages: "disable"
pg_pg_statsinfo_log_expired_date: 31 # original parameter
pg_pg_statsinfo_log_maintenance_command: "/usr/pgsql-{{ pgdg_version|regex_replace('-.*', '') }}/bin/archive_pglog.sh %l {{pg_pg_statsinfo_log_expired_date }}"
