---
# file: roles/postgresql/handlers/main.yml
- name: postgresql restart
  service:
    name: "postgresql-{{ pgdg_version|regex_replace('-.*', '') }}.service"
    state: restarted
    daemon_reload: yes
